# Generated by Django 5.2.17 on 2026-08-31 05:55

import django.db.models.deletion
import shipments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, unique=True, verbose_name='Haydovchi')),
                ('phone', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Telefon raqam')),
                ('tg_id', models.IntegerField(verbose_name='Telegram ID')),
                ('plate_number', models.CharField(max_length=50, unique=True, verbose_name='Fura raqami')),
            ],
            options={
                'verbose_name': 'Haydovchi',
                'verbose_name_plural': 'Haydovchilar',
                'ordering': ['plate_number'],
            },
        ),
        migrations.CreateModel(
            name='LoadingCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Shahar nomi')),
            ],
            options={
                'verbose_name': 'Yuklash shahri',
                'verbose_name_plural': 'Yuklash shaharlari',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Marshrut nomi')),
            ],
            options={
                'verbose_name': 'Marshrut',
                'verbose_name_plural': 'Marshrutlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name="Jo'natuvchi nomi")),
            ],
            options={
                'verbose_name': "Jo'natuvchi",
                'verbose_name_plural': "Jo'natuvchilar",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TransportCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Transport firmasi nomi')),
            ],
            options={
                'verbose_name': 'Transport firmasi',
                'verbose_name_plural': 'Transport firmalari',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_code', models.CharField(blank=True, db_index=True, editable=False, help_text='Avtomatik generatsiya qilinadi (masalan: ATLG-0001)', max_length=20, unique=True, verbose_name="Jo'natma ID")),
                ('recipient', models.CharField(max_length=255, verbose_name='Qabul qiluvchi')),
                ('product', models.CharField(max_length=255, verbose_name='Tovar')),
                ('img', models.ImageField(upload_to=shipments.models.client_image_path, verbose_name='Rasm')),
                ('status', models.CharField(choices=[('shipping', 'Yuklashda'), ('at_border', "Ulug'chat/Xargosda"), ('reloading', 'Qayta yuklashda'), ('delivered', 'Yetkazildi')], db_index=True, default='shipping', max_length=20, verbose_name='Status')),
                ('planned_shipping_date', models.DateField(verbose_name="Jo'natish sanasi (reja)")),
                ('actual_shipping_date', models.DateField(blank=True, null=True, verbose_name="Jo'natish sanasi (fakt)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracking.client', verbose_name='Mijoz')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='shipments.driver', verbose_name='Haydovchi')),
                ('loading_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='shipments.loadingcity', verbose_name='Yuklash shahri')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='shipments.route', verbose_name='Marshrut')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='shipments.sender', verbose_name="Jo'natuvchi")),
                ('transport_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='shipments.transportcompany', verbose_name='Transport firmasi')),
            ],
            options={
                'verbose_name': "Jo'natma",
                'verbose_name_plural': "Jo'natmalar",
                'ordering': ['-planned_shipping_date', 'shipment_code'],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_status', models.CharField(choices=[('shipping', 'Yuklashda'), ('at_border', "Ulug'chat/Xargosda"), ('reloading', 'Qayta yuklashda'), ('delivered', 'Yetkazildi')], max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='shipments.shipment', verbose_name="Jo'natma")),
            ],
            options={
                'verbose_name': 'Bosqich',
                'verbose_name_plural': 'Bosqichlar',
                'ordering': ['shipment', 'created_at'],
            },
        ),
    ]
