# Generated by Django 5.2.17 on 2026-08-14 12:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Ism va familiya')),
                ('phone', models.CharField(max_length=32, unique=True, verbose_name='Telefon raqami')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'Mijoz',
                'verbose_name_plural': 'Mijozlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(db_index=True, help_text='Track-nomer, masalan: ATL-24081', max_length=32, unique=True, validators=[django.core.validators.RegexValidator(message="Track-nomerda faqat harf, raqam va tire (-) bo'lishi mumkin.", regex='^[A-Za-z0-9\\-]+$')])),
                ('origin', models.CharField(max_length=120, verbose_name='Qayerdan')),
                ('destination', models.CharField(max_length=120, verbose_name='Qayerga')),
                ('current_status_category', models.CharField(choices=[('accepted', 'Qabul qilindi (Xitoy sklad)'), ('customs', "Chegaradan o'tmoqda"), ('in_transit', "Yo'lda"), ('arrived_warehouse', 'Toshkent skladiga yetib keldi'), ('out_for_delivery', 'Yetkazib berish jarayonida'), ('delivered', 'Yetkazib berildi'), ('custom', "Boshqa (o'z matni)")], default='accepted', max_length=20, verbose_name='Joriy status')),
                ('current_status_text', models.CharField(blank=True, max_length=200, verbose_name='Joriy status matni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cargos', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan admin')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargos', to='tracking.client', verbose_name='Mijoz')),
            ],
            options={
                'verbose_name': 'Yuk',
                'verbose_name_plural': 'Yuklar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CargoStatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_category', models.CharField(choices=[('accepted', 'Qabul qilindi (Xitoy sklad)'), ('customs', "Chegaradan o'tmoqda"), ('in_transit', "Yo'lda"), ('arrived_warehouse', 'Toshkent skladiga yetib keldi'), ('out_for_delivery', 'Yetkazib berish jarayonida'), ('delivered', 'Yetkazib berildi'), ('custom', "Boshqa (o'z matni)")], max_length=20, verbose_name='Status')),
                ('custom_text', models.CharField(blank=True, max_length=200, verbose_name='Maxsus matn')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='Joylashuv')),
                ('comment', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tracking.cargo', verbose_name='Yuk')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo_status_updates', to=settings.AUTH_USER_MODEL, verbose_name='Admin')),
            ],
            options={
                'verbose_name': 'Status yangilanishi',
                'verbose_name_plural': 'Status tarixi',
                'ordering': ['created_at'],
            },
        ),
    ]
