# Generated by Django 5.2.17 on 2026-08-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='Telegram ID'),
        ),
    ]
